"""Add tournament support with blinds and rebuy control

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2025-12-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d4e5f6a7b8'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.String(length=20), nullable=False, server_default='cash'))
        batch_op.add_column(sa.Column('blind_structure', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blind_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rebuy_limit', sa.Integer(), nullable=True, server_default='2'))
        batch_op.add_column(sa.Column('rebuy_until_level', sa.Integer(), nullable=True, server_default='6'))
        batch_op.add_column(sa.Column('current_level', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rebuys_used', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('rebuys_used')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('current_level')
        batch_op.drop_column('rebuy_until_level')
        batch_op.drop_column('rebuy_limit')
        batch_op.drop_column('blind_duration')
        batch_op.drop_column('blind_structure')
        batch_op.drop_column('game_type')

    # ### end Alembic commands ###
